name: pangaea_bus
description: A Kafka-style event streaming broker for Flutter micro-apps enabling decoupled communication between features.
version: 0.0.1
homepage: https://github.com/demola234/pangaea_bus
repository: https://github.com/demola234/pangaea_bus
issue_tracker: https://github.com/demola234/pangaea_bus/issues
documentation: https://github.com/demola234/pangaea_bus/wiki

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0
  collection: ^1.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0